data:
  fmeval: True
  kg_network_index: 1
  low_rating_thres: 0.0
  binarized_rating_thres: 3.0


eval:
  val_metrics: [auc, logloss]
  test_metrics: [auc, logloss]

model:
  embed_dim: 64
  weight_decay: 1e-7

  n_iter: 2
  neighbor_sample_size: 4
  aggregator_type: sum 
  ls_weight: 1.0