data:
  kg_network_index: 1
  fmeval: True
  low_rating_thres: 0.0
  binarized_rating_thres: 4.0

eval:
  val_metrics: [auc, logloss]
  test_metrics: [auc, logloss]

train:
  weight_decay: 1e-6
  batch_size: 2048
  negative_count: 1

model:
  embed_dim: 64
  using_all_hops: True
  item_update_mode: plus_transform  # how to update item at the end of each hop
  kge_weight: 0.01
  n_memory: 16 # size of ripple set for each hop
  n_hop: 2 # maximum hops
