data:
  split_ratio: [0.8, 0.1, 0.1]

eval:
  batch_size: 128
  cutoff: [20, 10, 5]

model:
  aug_type: 'ED'
  embed_dim: 64
  n_layers: 3
  l2_reg_weight: 1e-4
  negative_count: 1
  ssl_ratio: 0.1
  ssl_reg: 0.1
  temperature: 0.2

train:
  batch_size: 2048
  early_stop_patience: 100
  epochs: 1000
  learning_rate: 0.001
