data:
  split_ratio: [0.8, 0.1, 0.1]

eval:
  cutoff: [20, 10, 5]

model:
  embed_dim: 64
  eps: 0.1
  n_layers: 3

  l2_reg_weight: 1e-4
  cl_neg_type: all
  cl_weight: 0.5
  temperature: 0.2


train:
  batch_size: 2048
  early_stop_patience: 100
  epochs: 1000
  eval_batch_size: 128
  learning_rate: 0.001
