
data:
  split_mode: user
  split_ratio: [1.0]
  max_seq_len: 10


eval:
  batch_size: 1024
  predict_topk: 100
  test_metrics: [recall, precision, map, ndcg, mrr, hit]
  val_metrics: [mrr, recall, precision, ndcg]
  cutoff: [100, 200, 300]
  topk: 300


model:
  embed_dim: 128
  n_v: 6
  n_h: 16
  dropout: 0.25
  loss_func: softmax


train:
  negative_count: ~
  weight_decay: 0.0

  batch_size: 1024
  early_stop_patience: 10
  epochs: 300
  init_method: default
  init_range: 0.02
  negative_count: ~
  scheduler: onplateau
  pretrained_embed_file: ~
  learning_rate: 0.001