eval:
  batch_size: 128
  cutoff: [20, 50, 10, 5]

model:
  # transformer
  activation: 'gelu'
  dropout_rate: 0.5
  hidden_size: 64
  head_num: 2
  layer_norm_eps: 1e-12
  layer_num: 1
  # contrastive
  temperature: 1.0
  augment_type: item_crop  # item_crop, item_mask, item_reorder
  tau: 0.2
  cl_weight: 0.1

train:
  batch_size: 256
  early_stop_patience: 40
  epochs: 1000
  init_method: normal
  negative_count: 1
