eval:
  batch_size: 128
  cutoff: [20, 50, 10, 5]


model:
  # transformer
  hidden_size: 64
  layer_num: 1
  head_num: 2
  dropout_rate: 0.5
  activation: 'gelu'
  layer_norm_eps: 1e-12

  # contrastive
  temperature: 1.0
  insert_rate: 0.5
  substitute_rate: 0.05
  cl_weight: 0.1
  augment_threshold: 12
  augment_type_for_short: 'SIMRC'
  augmentation_warm_up_epochs: 5


train:
  batch_size: 256
  epochs: 1000
  early_stop_patience: 40
  init_method: normal
  negative_count: 1



