eval:
  batch_size: 32
  test_metrics: [auc, logloss]
  val_metrics: [auc, logloss]

model:
  activation: dice
  attention_mlp: [128, 64]
  batch_norm: True
  dropout: 0.3
  embed_dim: 128
  fc_mlp: [128, 64, 64]

train:
  batch_size: 256
  negative_count: 20

