data:
  split_mode: user
  split_ratio: [1.0]

eval:
  batch_size: 1024
  predict_topk: 100
  test_metrics: [recall, precision, map, ndcg, mrr, hit]
  val_metrics: [mrr, recall, precision, ndcg]
  cutoff: [100, 200, 300]
  topk: 300

model:
  embed_dim: 128
  hidden_size: 256
  dropout_rate: [0.25, 0.5]
  layer_num: 1
  loss_func: softmax

train:
  batch_size: 1024
  early_stop_patience: 10
  epochs: 100
  init_method: default
  negative_count: ~
  scheduler: onplateau