data:
  split_mode: user
  split_ratio: [1.0]
  max_seq_len: 10

eval:
  batch_size: 1024
  predict_topk: 100
  test_metrics: [recall, precision, map, ndcg, mrr, hit]
  val_metrics: [mrr, recall, precision, ndcg]
  cutoff: [100, 200, 300]
  topk: 300

model:
  # transformer
  embed_dim: &dim 128
  id_embed_dim: 128
  activation: 'gelu'
  dropout_rate: 0.5
  hidden_size: 256
  head_num: 2
  layer_norm_eps: 1e-12
  layer_num: 3
  loss_func: softmax
  reverse_pos: True

  text_id_concat: False
  item_layer_norm: False
  item_layers: [768, *dim]
  item_dropout: 0.0
  item_title_vectors: /root/autodl-tmp/xiaolong/WorkSpace/Amazon-KDDCUP-23/data_for_recstudio/DE_data/DE_product_title_vectors.npy

train:
  batch_size: 1024
  early_stop_patience: 10
  epochs: 300
  init_method: default
  init_range: 0.02
  negative_count: ~
  scheduler: onplateau
  pretrained_embed_file: ~
  learning_rate: 0.001
  grad_clip_norm: 10
  # pretrained_embed_file: /root/autodl-tmp/huangxu/Amazon-KDDCUP-23/co-occurrence_graph/graph_emb_128.pkl
  # scheduler: onplateau
  # weight_decay: 1e-6
