data:
  split_mode: user
  split_ratio: [1.0]

eval:
  batch_size: 512
  predict_topk: 100
  test_metrics: [recall, precision, map, ndcg, mrr, hit]
  val_metrics: [mrr, recall, precision, ndcg]
  cutoff: [100, 150, 50]
  topk: 150

model:
  # transformer
  embed_dim: 128
  activation: 'gelu'
  dropout_rate: 0.5
  hidden_size: 256
  head_num: 2
  layer_norm_eps: 1e-12
  layer_num: 1
  loss_func: CanSoftmax

train:
  batch_size: 1024
  early_stop_patience: 10
  epochs: 100
  init_method: normal
  negative_count: 1
