data:
  split_mode: user
  split_ratio: [1.0]
  max_seq_len: 10

eval:
  batch_size: 1024
  predict_topk: 100
  test_metrics: [recall, precision, map, ndcg, mrr, hit]
  val_metrics: [mrr, recall, precision, ndcg]
  cutoff: [100]
  topk: 100

model:
  # transformer
  embed_dim: 128
  activation: 'gelu'
  dropout_rate: 0.5
  hidden_size: 256
  head_num: 2
  layer_norm_eps: 1e-12
  layer_num: 1
  loss_func: cansoftmax
  reverse_pos: 0
  sasrec_ckpt_path: /root/autodl-tmp/xiaolong/WorkSpace/Amazon-KDDCUP-23/saved/SASRec_Next/kdd_cup_2023_UK/A100/2023-04-14-12-06-32_UK_best.ckpt
  retriver_ckpt_path: /root/autodl-tmp/xiaolong/WorkSpace/Amazon-KDDCUP-23/saved/SASRec_Next/kdd_cup_2023_UK/A100/2023-04-14-12-06-32_UK_best.ckpt
  retriver_name: SASRec_Next
  input_dropout: 0.75

train:  
  train_check: False
  batch_size: 1024
  early_stop_patience: 10
  epochs: 100
  init_method: normal
  negative_count: ~
  scheduler: onplateau
  pretrained_embed_file: ~
  # candidates strategy
  candidate_rand: False
  candidate_strategy: sasrec  # [sasrec, co_graph, sasrec+co_graph]
  num_candidates: 150
  # pretrained_embed_file: /root/autodl-tmp/huangxu/Amazon-KDDCUP-23/co-occurrence_graph/graph_emb_128.pkl
  # scheduler: onplateau
  # weight_decay: 1e-6
